# Generated by Django 4.0.3 on 2022-10-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAPIapp', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
    ]
