# Generated by Django 4.0.3 on 2022-10-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAPIapp', '0005_remove_orderitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedorder',
            old_name='maal',
            new_name='items',
        ),
    ]
