# Generated by Django 4.0.3 on 2022-10-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAPIapp', '0006_rename_maal_placedorder_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
