# Generated by Django 4.0.3 on 2022-10-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAPIapp', '0008_orderitem_image_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
