# Generated by Django 4.0.3 on 2022-10-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAPIapp', '0009_alter_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
