# Generated by Django 4.0.3 on 2022-11-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAPIapp', '0010_remove_orderitem_image_remove_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(),
        ),
    ]
