# Generated by Django 4.0.3 on 2022-11-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAPIapp', '0011_alter_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
